theta<-runif(100000)
y<-rbinom(100000,10,prob=theta)
hist(y)
df<-data.frame(theta = theta, y = y)
View(df)
library(ggplot2)
h<- ggplot(df,aes(theta,y))
h + geom_density2d()
h + geom_density2d_filled()
h + geom_point()
